name: github-actions-slack-notifier
description: Slack notifications for github actions workflows

inputs:
    app_name:
      description: Name of tenant app_name to deploy to, e.g. testapp1
      required: true
      type: string
      default: ${{ github.repository }}
    env_name:
      description: Name of tenant env to deploy to, e.g. dev
      required: true
      type: string
      default: ${{github.ref}}
    type:
      description: Message type to be sent, supported values 'start', 'end', 'failed', 'custom'
      required: true
      type: string
      default: end
    channel_id:
      description: Slack channel id to send messages
      required: true
      type: string
    slack_bot_token:
      description: Slack bot token oauth secret
      required: true
      type: string
    ref:
      description: Deployment ref
      required: false
      type: string
    message:
      description: Custom message when inputs.type is set to 'custom'
      required: false
      type: string
      default: ':ok_hand: Action on branch ${{github.ref}} is triggered'
    color:
      description: The color of the slack message
      required: false
      type: string
      default: 'default'
    mentions:
      description: Slack users or groups to mention in the message
      required: false
      type: string
      default: ''
    update_ts:
      description: Message ts for updating sent messages
      required: false
      type: string
outputs:
  ts:
    description: Slack ts for updating messages
    value: ${{ steps.slack.outputs.ts }}

runs:
  using: composite
  steps:
    - id: slack
      uses: slackapi/slack-github-action@v1.24.0
      env:
        SLACK_BOT_TOKEN: ${{ inputs.SLACK_BOT_TOKEN }}
        MESSAGE: >-
          {
            "start": {
              "attachments": [
                {
                  "color": "${{ inputs.color == 'default' && 'default' || '#dbab09' }}",
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: start",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy started - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            },
            "end": {
              "attachments": [
                {
                  "color": "${{ inputs.color == 'default' && 'default' || '#28a745' }},
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: end",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy complete - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            },
            "failed": {
              "attachments": [
                {
                  "color": "${{ inputs.color == 'default' && 'default' || '#a72841' }},
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: failed",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: Deploy failed - ${{ inputs.ref }} ${{ inputs.mentions }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]         
            },
            "default": {
              "attachments": [
                {
                  "color": "${{ job.status == 'success' && 'good' || job.status == 'failure' && 'danger' || 'warning' }}",
                  "fields": [
                    {
                      "title": "Job",
                      "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} | ${{ github.job }}>",
                      "short": true
                    },
                    {
                      "title": "Repo",
                      "value": "<https://github.com/${{ github.repository }} | ${{ github.repository }}>",
                      "short": true
                    },
                    {
                      "title": "${{ github.event_name == 'pull_request' && 'Pull Request' || 'Branch' }}",
                      "value": "${{ github.event_name == 'pull_request' && format('<{0} | {1}>', github.event.pull_request.html_url, github.event.pull_request.title) || format('<https://github.com/{0}/commit/{1} | {2}>', github.repository, github.sha, env.BRANCH)}}",
                      "short": true
                    },
                    {
                      "title": "Event",
                      "value": "${{ github.event_name }}",
                      "short": true
                    }
                  ],
                  "footer_icon": "https://github.githubassets.com/favicon.ico",
                  "footer": "<https://github.com/${{ github.repository }} | ${{ github.repository }}>",
                  "ts": ${{ steps.timestamp-step.outputs.timestamp }}
                }
              ]
            },
            "custom": {
              "attachments": [
                {
                  "color": "${{ inputs.color == 'default' && 'default' || '#28a745' }},
                  "fallback": "${{ inputs.app_name }} ${{ inputs.env_name }}: custom",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "${{ inputs.app_name }} ${{ inputs.env_name }}: ${{ inputs.message }}"
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Github Actions",
                          "emoji": true
                        },
                        "value": "click",
                        "url": "${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}",
                        "action_id": "button-action"
                      }
                    }
                  ]
                }
              ]
            }
          }
      with:
        channel-id: ${{ inputs.channel_id }}
        payload: ${{ toJSON(fromJson(env.MESSAGE)[inputs.type]) }}
        update-ts: ${{ inputs.update_ts }}